
name: 👔 Check formatting

on:
    pull_request:
    push:
        branches: ["main", "master", "develop", "release"]

env:
    CARGO_TERM_COLOR: always

jobs:
    check_format:
        name: 👔 Check formatting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      src-tauri/target/
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            - name: Check Formatting
              run: cd src-tauri/ ; cargo fmt -- --verbose --check --color auto
