name: 👔 Check formatting

on:
    pull_request:
    push:
        branches: ["main", "master", "develop", "release"]

env:
    CARGO_TERM_COLOR: always

jobs:
    check_format:
        name: 👔 Check formatting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Restore dependencies
              id: cargo
              uses: actions/cache/restore@v3
              with:
                path: |
                    ~/.cargo/bin/
                    ~/.cargo/registry/index/
                    ~/.cargo/registry/cache/
                    ~/.cargo/git/db/
                    src-tauri/target/
                key: ${{ runner.os }}-cargo-format-${{ hashFiles('**/Cargo.lock') }}
            - name: Check Formatting
              run: cd src-tauri/ ; cargo fmt -- --verbose --check --color auto
            - name: Save dependencies
              id: cargo-save
              uses: actions/cache/save@v3
              with:
                path: |
                    ~/.cargo/bin/
                    ~/.cargo/registry/index/
                    ~/.cargo/registry/cache/
                    ~/.cargo/git/db/
                    src-tauri/target/
                key: ${{ runner.os }}-cargo-format-${{ hashFiles('**/Cargo.lock') }}
