
name: 🖋  Check linting

on:
    pull_request:
    push:
        branches: ["main", "master", "develop", "release"]

env:
    CARGO_TERM_COLOR: always

jobs:
    check_lint_rust:
        name: 🖋 Check linting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Restore dependencies
              id: cargo
              uses: actions/cache/restore@v3
              with:
                path: |
                    ~/.cargo/bin/
                    ~/.cargo/registry/index/
                    ~/.cargo/registry/cache/
                    ~/.cargo/git/db/
                    src-tauri/target/
                key: ${{ runner.os }}-cargo-lint-${{ hashFiles('**/Cargo.lock') }}
            - name: install dependencies (ubuntu only)
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf libudev-dev
            - name: Check linting
              run: |
                  rustup component add clippy
                  set env RUSTFLAGS="-Dwarnings"
                  cd src-tauri/ ; cargo clippy --workspace -- -D warnings
            - name: Save dependencies
              id: cargi-save
              uses: actions/cache/save@v3
              with:
                path: |
                    ~/.cargo/bin/
                    ~/.cargo/registry/index/
                    ~/.cargo/registry/cache/
                    ~/.cargo/git/db/
                    src-tauri/target/
                key: ${{ runner.os }}-cargo-lint-${{ hashFiles('**/Cargo.lock') }}
