
name: 🧪 Tests
on:
    pull_request:
    push:
        branches: ["main", "master", "develop", "release"]

env:
    CARGO_TERM_COLOR: always

jobs:
    test:
        strategy:
          matrix:
            os: [ubuntu-latest, macos-latest]
            toolchain: [stable]
        name: 🧪 Run tests
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Install latest ${{ matrix.toolchain }}
              uses: actions-rs/toolchain@v1
              with:
                toolchain: ${{ matrix.toolchain }}
            - name: Restore dependencies
              id: cargo
              uses: actions/cache/restore@v3
              with:
                path: |
                    ~/.cargo/bin/
                    ~/.cargo/registry/index/
                    ~/.cargo/registry/cache/
                    ~/.cargo/git/db/
                    src-tauri/target/
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            - name: install dependencies (ubuntu only)
              if: matrix.os == 'ubuntu-latest'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf libudev-dev
            - name: Run tests
              run: cd src-tauri/ ; cargo test
            - name: Save dependencies
              id: cargi-save
              uses: actions/cache/save@v3
              with:
                path: |
                    ~/.cargo/bin/
                    ~/.cargo/registry/index/
                    ~/.cargo/registry/cache/
                    ~/.cargo/git/db/
                    src-tauri/target/
                key: ${{ runner.os }}-cargo-tests-${{ hashFiles('**/Cargo.lock') }}